name: CI
on: push

jobs:
    check-style:
        name: Check code style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run check-style

    frontend-build:
        name: Build frontend
        runs-on: ubuntu-latest
        needs: check-style

        defaults:
            run:
                working-directory: frontend

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run build:ci
            - uses: actions/upload-artifact@main
              with:
                  name: frontend-build
                  path: frontend/build

    frontend-test:
        name: Test frontend
        runs-on: ubuntu-latest
        needs: frontend-build

        defaults:
            run:
                working-directory: frontend

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run test:ci

    backend-build:
        name: Build backend
        needs: check-style
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run lint:ci
            - run: npm run build
            - uses: actions/upload-artifact@main
              with:
                  name: backend-build
                  path: backend/build

    backend-test:
        name: Test backend
        needs: backend-build
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run test:ci
            - uses: codecov/codecov-action@v2
              with:
                  files: ./coverage/lcov.info
                  flags: unittests,backend
                  fail_ci_if_error: true
