name: Deploy backend

on:
    push:
        branches:
            - main
        paths:
            - './backend/**.*'
            - './.github/**.*'

    workflow_dispatch:

env:
    PROJECT_ID: ${{ secrets.GCP_PROJECT }}
    PROJECT_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    PROJECT_WIP: ${{ secrets.GCP_PROJECT_WIP }}
    PROJECT_REGISTRY: ${{ secrets.GAR_REGISTRY }}
    IMAGE: ${{ secrets.BACKEND_IMAGE }}

jobs:
    check-style:
        name: Check code style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run check-style

    backend-build:
        name: Build backend
        needs: check-style
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run lint:ci
            - run: npm run build

    backend-test:
        name: Test backend
        needs: backend-build
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run test:ci
            - uses: codecov/codecov-action@v2
              with:
                  flags: unittests,backend
                  fail_ci_if_error: true

    backend-push-gcp:
        name: Build and push backend to GAR
        needs: backend-test
        runs-on: ubuntu-latest

        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            - uses: actions/checkout@v2

            - id: 'auth'
              name: 'Authenticate to Google Cloud'
              uses: 'google-github-actions/auth@v0'
              with:
                  workload_identity_provider: '$PROJECT_WIP'
                  service_account: '$PROJECT_SERVICE_ACCOUNT'
                  token_format: 'access_token'

            - name: Login to GAR
              uses: docker/login-action@v1
              with:
                  registry: $PROJECT_REGISTRY
                  username: oauth2accesstoken
                  password: ${{ steps.auth.outputs.access_token }}

            - name: Build image
              run: |
                  docker build \
                    --tag "$PROJECT_REGISTRY/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
                    --build-arg GITHUB_SHA="$GITHUB_SHA" \
                    --build-arg GITHUB_REF="$GITHUB_REF" \
                    ./backend

            - name: Push image
              run: docker push "$PROJECT_REGISTRY/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
