name: Test frontend
on:
    push:
        branches-ignore:
            - 'main'
        paths:
            - 'frontend/**'
            - '.github/workflows/test_frontend.yml'

jobs:
    check-style:
        name: Check code style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run check-style-frontend

    frontend-build:
        name: Build frontend
        runs-on: ubuntu-latest
        needs: check-style

        defaults:
            run:
                working-directory: frontend

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run build:ci

    frontend-test:
        name: Test frontend
        runs-on: ubuntu-latest
        needs: frontend-build

        defaults:
            run:
                working-directory: frontend

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run test:ci
